#!/usr/bin/env bash
# Export the local Ceph changes as a patch series, without the boost build
# output that BuildBoost.cmake generates inside the source tree. Those files
# were tracked before .gitignore covered them, so older commits still carry
# them and format-patch would emit them.
#
# Verifies afterwards that the series applies to the vanilla commit.
#
#   usage: scripts/export-patches.sh [number-of-commits]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src/ceph"
OUT="$ROOT/patches"
COUNT="${1:-7}"

rm -f "$OUT"/*.patch
git -C "$SRC" format-patch -"$COUNT" -o "$OUT" >/dev/null

python3 - "$OUT" <<'PY'
import pathlib, re, sys

out = pathlib.Path(sys.argv[1])
noise = re.compile(
    r"^src/boost/(bin\.v2/|stage/|project-config\.jam|b2$|bjam$)"  # generated by BuildBoost
    r"|(^|/)\.DS_Store$"                                            # Finder droppings
    r"|^\.gitignore$"                                               # our own housekeeping
)

for patch in sorted(out.glob("*.patch")):
    text = patch.read_text()
    head, sep, body = text.partition("diff --git ")
    if not sep:
        continue
    kept, dropped = [], 0
    for chunk in body.split("\ndiff --git "):
        m = re.match(r"a/(\S+) b/(\S+)", chunk)
        path = m.group(2) if m else ""
        if noise.match(path):
            dropped += 1
        else:
            kept.append(chunk)
    if not kept:
        patch.unlink()
        print(f"{patch.name}: nur generierte Dateien -> entfernt")
        continue
    rebuilt = head + "diff --git " + "\ndiff --git ".join(kept)
    if not rebuilt.endswith("\n"):
        rebuilt += "\n"
    patch.write_text(rebuilt)
    files = [re.match(r"a/(\S+) b/(\S+)", c).group(2) for c in kept
             if re.match(r"a/(\S+) b/(\S+)", c)]
    note = f" ({dropped} generierte Abschnitte entfernt)" if dropped else ""
    print(f"{patch.name}: {len(files)} Datei(en){note}")
    for f in files:
        print(f"    {f}")
PY

# renumber so the series has no gaps if a patch was dropped entirely
i=1
for p in $(ls "$OUT"/*.patch 2>/dev/null | sort); do
  new="$OUT/$(printf '%04d' $i)-$(basename "$p" | sed 's/^[0-9]*-//')"
  [ "$p" = "$new" ] || mv "$p" "$new"
  i=$((i + 1))
done

# verification: does the series apply to the untouched upstream tree?
VANILLA="$(git -C "$SRC" log --format=%H --grep='^vanilla ceph' | tail -1)"
if [ -n "$VANILLA" ]; then
  TMP="$(mktemp -d)"
  git -C "$SRC" archive "$VANILLA" | tar -x -C "$TMP"
  ok=yes
  for p in "$OUT"/*.patch; do
    git -C "$TMP" apply --check "$p" 2>/dev/null || { echo "FAILS TO APPLY: $(basename "$p")"; ok=no; }
    git -C "$TMP" apply "$p" 2>/dev/null || true
  done
  rm -rf "$TMP"
  [ "$ok" = yes ] && echo && echo "verified: the series applies cleanly to $(echo "$VANILLA" | cut -c1-8)"
fi
